global:
  scrape_interval: 3s
  external_labels:
    monitor: 'shahsoftsol'
scrape_configs:
  - job_name: 'Prometheus' 
    static_configs: 
      - targets: ['165.22.217.139:9090'] ## IP Address of the localhost
  - job_name: 'Tailortrails' 
    static_configs:
      - targets: ['3.95.122.234:8080']
