version: '3'
services:
    google-containers:
        volumes:
            - '/:/rootfs:ro'
            - '/var/run:/var/run:ro'
            - '/sys:/sys:ro'
            - '/var/lib/docker/:/var/lib/docker:ro'
            - '/dev/disk/:/dev/disk:ro'
        ports:
            - '8080:8080'
        container_name: cadvisor
        image: 'google/cadvisor'
        command:
            #- '--docker=tcp://socket-proxy:2375'
            - '--housekeeping_interval=15s'
            - '--docker_only=true'
            - '--disable_metrics=disk,network,tcp,udp,percpu,sched,process'


    alertmanager:
        image: prom/alertmanager
        ports:
        - '9093:9093'
        volumes:
        - './alertmanager/:/etc/alertmanager/'
        restart: always
        command:
        - '--config.file=/etc/alertmanager/config.yml'
        - '--storage.path=/alertmanager'
    node-exporter:
        image: prom/node-exporter
        volumes:
        - '/proc:/host/proc:ro'
        - '/sys:/host/sys:ro'
        - '/:/rootfs:ro'
        command:
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.ignored-mount-points'
        - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
        - '9100:9100'
        restart: always
