version: '3'
services:

      google-containers:
        volumes:
            - '/:/rootfs:ro'
            - '/var/run:/var/run:ro'
            - '/sys:/sys:ro'
            - '/var/lib/docker/:/var/lib/docker:ro'
            - '/dev/disk/:/dev/disk:ro'
        command: 
           # - '--docker=tcp://socket-proxy:2375'
            - --allow_dynamic_housekeeping=true
            - '--housekeeping_interval=5s'
            - --global_housekeeping_interval=5s
            - '--docker_only=true'
            - '--disable_metrics=disk,network,tcp,udp,percpu,sched,process'
        deploy:
          resources:
            limits:
              cpus: '0.10'
              memory: 50M
        privileged: true
        ports:
            - '8080:8080'
        container_name: cadvisor
        image: 'google/cadvisor'
        restart : unless-stopped
      node-exporter:
        image: prom/node-exporter
        volumes:
        - '/proc:/host/proc:ro'
        - '/sys:/host/sys:ro'
        - '/:/rootfs:ro'
        deploy:
          resources:
            limits:
              cpus: '0.05'
              memory: 50M
        command:
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.ignored-mount-points'
        - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
        - '9100:9100'
        restart: unless-stopped
